@startuml
title Ratings calculation for a single race type
(*) --> "divide races by market"
"divide races by market" --> "further divide races by date"
"further divide races by date" --> "calculate for each date"
note right
See "Race factor calculation for each date" and "Rating calculation for each race and date"
end note
"calculate for each date" --> "save the daily result into database"
@enduml