@startuml
(*) --> "get all the horses' runner records among related races"

"get all the horses' runner records among related races" --> "find out best, worst and average ratings"
note right
runnerRating = runnerFactor * raceFactor
end note
"find out best, worst and average ratings" --> (*)
@enduml