@startuml


title New Code Flow
note
 Input:  An upcoming race's key + Last X days for calculation
Output:  Ruf rating for every running record during the period (running record = combination of horse + race)
end note


:Get all the horses for this race;
:Get all the running records the horses were in;
repeat: pick a horse and its running records
:Calculate the runner factor for every running record;
repeat while (more data?) is (yes)
->no;


stop

@enduml