@startuml


title New Code Flow
note
 Input:  A target race's key + data period for calculation
Output:  Ruf ratings for all Runners during the period
end note

:Find out all the horses for the target race;
:Find out all the runners related to the horses during the period;
note right
Filter out races that are not compatible with the target race;
end note
repeat: pick a horse and its runners
:Calculate the runner factor for every runner;
repeat while (more data?) is (yes)
->no;
:Find out related races for every race;
note right
1. two races are related if they share a horse
2. incompatible races won't be related
end note
:Calculate all race factors in a big chunk function;
note right
Nobody totally understands the algorithm here
end note
repeat: pick a runner
:ruf_rating = runner_factor * race_factor;
repeat while (more data?) is (yes)

:output all the runners and their ruf ratings;

#Pink:calculate avg/best/worst/last ruf ratings for every horse;
note right
Not implemented in this project
end note

stop

@enduml